#!/bin/bash

pip install -e .
pip install nose nosexcover coverage pylint nose-exclude
nosetests --with-xunit --xunit-file=nosetests.xml --with-xcoverage --xcoverage-file=coverage.xml
pylint -f parseable stackato | tee pylint.out
